### PR TITLE
fix file_io operations to throw errors properly

### PR DESCRIPTION
**Pull request by settwi**
Sometimes file operations weren't properly finding which files were corrupted. So this fixes that by removing some of the multiprocessing and reapportioning function responsibilities.

### CODE REVIEW

**Comment by settwi** [comment]
Also ran `autopep8`

**Comment by masek014** [comment]
Thanks, looks good.

**Comment by settwi** [comment]
took you long enough 💀

**Comment by masek014** [comment]
This stuff is pretty low priority, man :sweat_smile:

**Pull request merged**
